theme = "hyde"

baseURL = "https://B1ackGh0st.github.io/isn"
languageCode = "en-us"
title = "Christopher Hart's Blog"
theme = "m10c"

[params]
  author = "B1ackGh0st"
  description = "A blog about all things technical."