baseURL = "https://b1ackgh0st.github.io/isn"
languageCode = "ru-ru"
title = "Тестовый сервер на Hugo"
theme = "hyde"

[params]
  author = "B1ackGh0st"
  description = "A blog about all things technical."